default: &default
  adapter: postgresql 
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  host: localhost
  username: postgres

development:
  <<: *default
  database: "dev"

test:
  <<: *default
  database: "test"
