# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 5387cc30b4d080cc8ec0febd4dabf1045c5c2d02fc8db4f5b91e0e3c49d7e928d7fa19d272d0e9b083300b64841816cfbf0b134b3b628e4d0094fae24ceecca7

test:
  secret_key_base: 284be95dfaadd0b5f79d344f79ae744e28851fb6b542fdab52131a6fbb7525eaf008a951b39e51d078cd8a84653bb7e38013e0710ebbc7a7962d3e5ef5d8af50

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
